# config/cucumber.yml
##YAML Template
---
mobile1: ADEVICENAME='mobile1'
mobile2: ADEVICENAME='mobile2'
mobile2: ADEVICENAME='mobile3'
mobile2: ADEVICENAME='mobile4'

default: -p html_report -p chrome -p dev
html_report: --format progress --format html --out=features_report.html