require "cucumber"
require "cucumber/rake/task"
require "open4"

desc 'Run parallel appium'
task :run_parallel, [:quantity] do |_task, args|
  count = 0
  args[:quantity].to_i.times do
    puts "Starting Appium server number #{count} "
    command =  "appium -p 472#{count} -pb 225#{count}"
    
    Dir.chdir('./') {
      pid, stdin, stdout, stderr = Open4::popen4(command)
      sleep 5

      if pid.zero?
        puts 'Appium server did not start'
        exit(false)
      else
        puts "Appium server is running with PID: #{pid}"
      end
    }

    run_test = "cucumber -p mobile#{count} --tags @test#{count} -f html -o ./reports/mobile#{count}.html"
    Open4::popen4(run_test)
    sleep 3

    count += 1
  end
end
