require "cucumber"
require "cucumber/rake/task"

@success = true

desc 'Start Emulator'
task :start_emulator, [:emulator_name] do |_task, args|
  puts "Starting emulator #{args[:emulator_name]}"
  sh "emulator -avd #{args[:emulator_name]} > /dev/null &"
end

def run_tests(platform, name, udid, port)
  
  sh("platform=\"#{platform}\" name=\"#{name}\" udid=\"#{udid}\" port=\"#{port}\"") do | success, _exit_code |
    @success &= success
  end
end

task :default => [:test_sauce]


task :mobile1 do
  run_tests('Android', 'mobile1','be2745f499ec7aec','4723')
end

task :mobile2 do
  run_tests('Android', 'mobile2','79b2b0a02578f8b7','4724')
end

task :teste do
sh 'cucumber'
end

multitask :test_darling => [
  :mobile1,
  :mobile2,
  :teste
] do
raise StandardError, "Tests failed!" unless @success
end
